
version: '3.4'

services:

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.15.2
    ports:
      - 8200:8200
      - 6060:6060
    environment:
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]
    networks:
      - elastic
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E apm-server.host=0.0.0.0:8200
        -E setup.kibana.host=kibana:5601
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.5.0
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.templates.enabled
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled= false
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: kibana:8.5.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elastic


networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
